<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>Glyphborn.Mapper</RootNamespace>
    <BaseOutputPath>$(SolutionDir)..\Glyphborn\tools\mapper</BaseOutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>Mapper.ico</ApplicationIcon>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
    <SignAssembly>False</SignAssembly>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>True</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Mapper.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Updater\Updater.csproj" />
  </ItemGroup>

</Project>